pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from version control
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build the code, replace with your build commands
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                // Run tests, replace with your testing commands
                sh 'npm test'
            }
        }
        
        stage('Deploy') {
            when {
                expression { currentBuild.resultIsBetterOrEqualTo('SUCCESS') }
            }
            steps {
                // Deploy the application, replaceb with your deployment commands
                sh 'npm deploy'
            }
        }
    }
    
    post {
        always {
            // Clean up or perform final tasks, regardless of the build result
            echo 'Pipeline finished.'
        }
    }
}
